//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH___LW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatoRefTech
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidatoRefTech()
        {
            this.CandidatoDetalhes = new HashSet<CandidatoDetalhe>();
        }
    
        public int CandidatoRefTechID { get; set; }
        public string CandidatoRefTechName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatoDetalhe> CandidatoDetalhes { get; set; }
    }
}
