//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH___LW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatoDetalhe
    {
        public int CandidatoID { get; set; }
        public string CandidatoNome { get; set; }
        public string CandidatoIdade { get; set; }
        public string CandidatoEmail { get; set; }
        public string CandidatoEndereco { get; set; }
        public Nullable<int> CandidatoTechID { get; set; }
    
        public virtual CandidatoRefTech CandidatoRefTech { get; set; }
    }
}
