//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH___LW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrevistaDetalhe
    {
        public int NomeID { get; set; }
        public string Descrevaumpoucosobrevocê { get; set; }
        public string Digiteoqueseusexchefesdiriamsobrevocê { get; set; }
        public string Digiteoquevocêsabesobreanossaempresaenossaculturaorganizacional { get; set; }
        public string Digiteoporquevocêdecidiusecandidataraestavaga { get; set; }
        public string Digiteoqueseuscolegasdetrabalhodiriamsobrevocê { get; set; }
        public string Digitequaissãoos_seus_pontos_fortesefracos { get; set; }
        public string DigitesobresuaexperiênciacomoDev { get; set; }
        public string Digiteoporquevocêquersairousaiudaúltimaempresa { get; set; }
    }
}
