//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH___LW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RHEntities1 : DbContext
    {
        public RHEntities1()
            : base("name=RHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandidatoDetalhe> CandidatoDetalhes { get; set; }
        public virtual DbSet<CandidatoRefTech> CandidatoRefTeches { get; set; }
        public virtual DbSet<Vaga> Vagas { get; set; }
        public virtual DbSet<VagaRefDetalhe> VagaRefDetalhes { get; set; }
    }
}
