//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH___LW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaga
    {
        public int VagaID { get; set; }
        public string VagaNome { get; set; }
        public Nullable<int> VagaDetalheID { get; set; }
    
        public virtual VagaRefDetalhe VagaRefDetalhe { get; set; }
    }
}
